# Generated by Django 3.2.3 on 2021-05-30 11:52

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField(db_index=True)),
                ('qr_picture', models.ImageField(upload_to=base.models.directory_path_qr)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_qr', to='base.establishmentmodel')),
            ],
        ),
    ]
