# Generated by Django 3.2.3 on 2021-05-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('text_button', models.TextField(db_index=True, max_length=400)),
                ('enable', models.BooleanField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_button', to='base.establishmentmodel')),
            ],
        ),
    ]
