# Generated by Django 3.2.3 on 2021-06-01 06:10

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_buttonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDishesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_category', to='base.establishmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=75)),
                ('price', models.IntegerField(db_index=True)),
                ('description', models.TextField(db_index=True, max_length=300)),
                ('dish_picture', models.ImageField(upload_to=base.models.directory_path_dish)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_dish', to='base.categorydishesmodel')),
            ],
        ),
    ]
