# Generated by Django 3.2.3 on 2021-06-01 14:00

import base.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categorydishesmodel_dishmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='dish_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=base.models.directory_path_dish),
        ),
    ]
