# Generated by Django 3.2.3 on 2021-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_dishmodel_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
