# Generated by Django 3.2.3 on 2021-06-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_buttonmodel_text_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('text_comment', models.TextField(db_index=True, max_length=200)),
                ('rate', models.IntegerField(db_index=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_comment', to='base.establishmentmodel')),
            ],
        ),
    ]
