# Generated by Django 3.2.3 on 2021-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='number_table',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
