# Generated by Django 3.2.3 on 2021-06-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_dishmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentmodel',
            name='link_tg',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='establishmentmodel',
            name='tg_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
