# Generated by Django 3.2.3 on 2021-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210605_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='telegram_chat',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
