# Generated by Django 3.2.3 on 2021-06-07 21:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_establishmentmodel_telegram_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('waiter', models.IntegerField(db_index=True, default=0)),
                ('menu', models.IntegerField(db_index=True, default=0)),
                ('feedback', models.IntegerField(db_index=True, default=0)),
                ('pieces', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), size=None)),
                ('count_users', models.IntegerField(db_index=True, default=0)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_stat', to='base.establishmentmodel')),
            ],
        ),
    ]
