# Generated by Django 3.2.3 on 2021-06-07 22:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_pieces_statisticmodel_users_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticmodel',
            name='users_ip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
