# Generated by Django 3.2.3 on 2021-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_statisticmonthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradvanced',
            name='bill_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='useradvanced',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradvanced',
            name='subscription_date',
            field=models.DateTimeField(null=True),
        ),
    ]
