# Generated by Django 3.2.3 on 2021-06-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20210609_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.TextField()),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
