# Generated by Django 3.2.3 on 2021-06-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradvanced',
            name='trial',
            field=models.BooleanField(default=True),
        ),
    ]
