# Generated by Django 3.2.3 on 2021-06-12 11:53

import base.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_useradvanced_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=base.models.user_directory_path),
        ),
    ]
