# Generated by Django 3.2.4 on 2021-06-20 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20210620_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentmodel',
            name='date_subscribe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishmentmodel',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradvanced',
            name='pay_establishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=0, size=None),
            preserve_default=False,
        ),
    ]
