# Generated by Django 3.2.4 on 2021-06-20 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210620_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvanced',
            name='pay_establishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=None),
        ),
    ]
