# Generated by Django 3.2.4 on 2021-06-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_useradvanced_pay_establishments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishmodel',
            options={'ordering': ['pk']},
        ),
    ]
