# Generated by Django 3.2.4 on 2021-06-21 04:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_dishmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvanced',
            name='pay_establishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
