# Generated by Django 3.2.4 on 2021-06-21 04:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_useradvanced_pay_establishments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvanced',
            name='pay_establishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
