# Generated by Django 3.2.4 on 2021-06-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_useradvanced_pay_establishments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradvanced',
            old_name='pay_establishments',
            new_name='establishments_pay',
        ),
    ]
